spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking_core_user_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

info:
  app:
    name: ${spring.application.name}

app:
  config:
    keycloak:
      server-url: http://localhost:8080/auth
      realm: giapp
      clientId: giapp-security
      client-secret: 3IPSWPeecTksgDq15qoGZvZlAneupNF9
  feign:
    client:
      core-banking: core-banking-service
